### ISSUE TITLE
Characters not Showing

### ISSUE THREAD

**Issue by HumanTree92** [ArkSeyonet/esx_identity#4]
Since updating to this esx_identity instead of the default one new players are running into a lot of issues. For example when they first join & create their character their characters clothing doesn't save. They are unable to take jobs b/c its creating them under the users DB but not in characters. 

In the ESX ORG Identity it saves their stuff in the Characters DB as well.

**Comment by ArkSeyonet** [comment]
The characters clothing is part of ESX Framework, not part of ESX Identity, and therefore it is not my issue. Contact the ESX Framework Team about your skins not saving.

I don't have any problems with jobs in my version of the script, because jobs should not have any interaction with the characters table. Finally, the characters table is redundant if you aren't using multiple characters.

All of these problems are problems involving functionality in other scripts not my scripts.
